services:
    sonar-scanner-version-tester:
        build:
            context: .
            args:
                SCANNER_VERSION: "${SCANNER_VERSION}"
                DOCKER_USER: "${DOCKER_USER}"
                DOCKER_UID: "${DOCKER_UID}"
                DOCKER_GID: "${DOCKER_GID}"
        env_file:
            - ./.env
        volumes:
            - ./src:/app/src:rw
